server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: gestionevenementseurika-1
          uri: lb://gestionevenementseurika-1
          predicates:
            - Path=/themes/**

        - id: users-micro-services-eurika
          uri: lb://users-micro-services-eurika
          predicates:
            - Path=/users/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
